project_id = "scoremore"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:5173/admin.html", "http://localhost:5173/student.html", "http://localhost:5173/reset-password.html"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.recovery]
subject = "Reset your account password"
content_path = "./supabase/templates/recovery.html"

[auth.email.notification.password_changed]
enabled = true
subject = "Your account password was changed"
content_path = "./templates/password_changed_notification.html"

[auth.email.notification.identity_linked]
enabled = true
subject = "A new sign-in method was linked"
content_path = "./templates/identity_linked_notification.html"

[auth.email.notification.mfa_factor_enrolled]
enabled = true
subject = "A verification method was added"
content_path = "./templates/mfa_factor_enrolled_notification.html"
